version: "3.7"

services:
  nginx:
    build:
      context: nginx
    ports:
      - 80:80
    depends_on:
      - backend
      - web
  web:
    build:
      context: web
      target: development
    command: sh entrypoint.sh
    volumes:
      - ./web:/usr/src/app
    depends_on:
      - backend
    ports:
      - 3000:3000
  backend:
    build:
      context: backend
      target: development
    command: sh entrypoint.sh
    volumes:
      - ./backend:/usr/src/app
    environment:
      APP_ADDRESS: "0.0.0.0"
      APP_PORT: 4000
      JWT_SECRET: jwt_secret
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: ah
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    depends_on:
      - postgres
    ports:
      - 4000:4000
  postgres:
    image: postgres:13.4
    environment:
      POSTGRES_DB: ah
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
