version: "3.7"

services:
  backend:
    build:
      context: backend
      target: development
    command: sh entrypoint.sh
    volumes:
      - ./backend:/usr/src/app
    environment:
      JWT_SECRET: jwt_secret
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: ah
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    depends_on:
      - postgres
  postgres:
    image: postgres:13.4
    environment:
      POSTGRES_DB: ah
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
